---
abstract: 'Updates dual-lived modules'
author:
  - 'Kevin W. Henwood <Khen1950fx@aol.com>'
build_requires:
  ExtUtils::MakeMaker: 5.50
configure_requires:
  ExtUtils::MakeMaker: 5.50
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: Perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Bundle-dualLived
name: Bundle-dualLived
no_index:
  directory:
    - inc
    - t
requires:
  CPAN: 0
version: 0.00_05
